'use client'

import { jsPDF } from 'jspdf'
import { FileDown } from 'lucide-react'

type Props = {
  paymentAmount: number
  paidOn: string
  studentName: string
  tutorName: string
  cycleLabel: string
}

export default function PaymentReceiptButton({ paymentAmount, paidOn, studentName, tutorName, cycleLabel }: Props) {
  function download() {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' })
    const m = 48
    let y = m
    doc.setFontSize(20)
    doc.text('Fee receipt', m, y)
    y += 36
    doc.setFontSize(11)
    doc.setTextColor(60, 60, 60)
    doc.text(`Issued by: ${tutorName}`, m, y)
    y += 20
    doc.text(`Date: ${new Date(paidOn).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}`, m, y)
    y += 28
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(12)
    doc.text(`Student: ${studentName}`, m, y)
    y += 22
    doc.text(`Billing cycle: ${cycleLabel}`, m, y)
    y += 22
    doc.setFontSize(14)
    doc.text(`Amount received: ₹${Math.round(paymentAmount).toLocaleString('en-IN')}`, m, y)
    y += 36
    doc.setFontSize(9)
    doc.setTextColor(100, 100, 100)
    doc.text('This is a simple record generated by Tuitionly — not a tax invoice.', m, y)
    doc.save(`receipt-${studentName.replace(/\s+/g, '-')}-${paidOn}.pdf`)
  }

  return (
    <button
      type="button"
      onClick={download}
      className="inline-flex items-center gap-1 text-xs font-medium text-zinc-600 hover:text-zinc-950"
    >
      <FileDown className="h-3.5 w-3.5" />
      Receipt
    </button>
  )
}
